### ISSUE TITLE
Dash between numbers e.g. สิบ-ยี่สิบ

### ISSUE THREAD

**Issue by ppnplus** [mishari/CV-Thai-Processor#1]
Keeping dash between numbers could mislead contributors. Most usually, the dash is said as ถึง.

**Comment by mishari** [comment]
I'm not sure, other times the dash is silent, for example, Krungthep-Lad Krabang trains are never read as "Krungthep thueng Lad Krabang"

**Comment by mishari** [comment]
Decided for now to remove all sentences with dashes in it, makes it easier.
